apiVersion: 1

datasources:
  - name: PostgreSQL_metrics_training
    type: postgres
    access: proxy
    url: db.:5432
    database: training_monitoring
    user: 'admin'
    secureJsonData:
      password: 'admin'
    jsonData:
      sslmode: 'disable'

  - name: PostgreSQL_metrics_batch
    type: postgres
    access: proxy
    url: db.:5432
    database: predict_monitoring
    user: 'admin'
    secureJsonData:
      password: 'admin'
    jsonData:
      sslmode: 'disable'
