apiVersion: 1

datasources:
  - name: Postgres_metrics_training
    type: postgres
    access: proxy
    url: db.:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: training_monitoring
      sslmode: 'disable'

  - name: PostgreSQL_metrics_prediction
    type: postgres
    access: proxy
    url: db.:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: predict_monitoring
      sslmode: 'disable'
