{
 "title": "Batch Prediction Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, drift_score FROM drift_prediction LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted Columns Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, share_of_drifted_columns FROM drift_dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift Detection Outcome",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, drift_detected FROM drift_prediction LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dataset Drift Detection Outcome",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT batch_date, dataset_drift FROM drift_dataset LIMIT 50 "
    }
   ]
  }
 ]
}