{
 "title": "Training dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Classification metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Train set",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  train_accuracy AS accuracy,\r\n  train_precision As precision,\r\n  train_recall As recall,\r\n  train_f1 AS f1_score\r\nfrom classification_metrics "
    }
   ]
  },
  {
   "title": "Validation set",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  val_accuracy AS Accuracy,\r\n  val_precision AS Precision,\r\n  val_recall AS Recall,\r\n  val_f1 AS f1_score\r\nfrom classification_metrics "
    }
   ]
  },
  {
   "title": "Number of columns",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT number_of_columns FROM drift_dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted columns",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT number_of_drifted_columns FROM drift_dataset LIMIT 50 "
    }
   ]
  },
  {
   "title": "Target drift",
   "type": "gauge",
   "description": "Target drift with threshold 0.1",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT drift_score FROM drift_target LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "gauge",
   "description": "Prediction drift with threshold 0.1",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT drift_score FROM drift_prediction LIMIT 50 "
    }
   ]
  }
 ]
}